---
- name: ensure os is up to date
  apt:
    update_cache: yes
    upgrade: full
    cache_valid_time: 300

- name: install packages
  apt: pkg={{ item }} state=present
  with_items:
    - bash-completion
    - curl
    - parted
    - python
    - htop
    - ncdu
  tags:
    - packages

- name: create a new primary partition for /dev/sdb
  parted:
    device: /dev/sdb
    number: 1
    state: present

- name: create an ext4 filesystem on /dev/sdb1
  filesystem:
    fstype: ext4
    dev: /dev/sdb1

- name: create storage mount
  mount:
    fstype: ext4
    src: /dev/sdb1
    path: /mnt/storage
    state: mounted

- name: chown storage mount
  file:
    path: /mnt/storage
    mode: 0777

- name: create a new primary partition for /dev/sdc
  parted:
    device: /dev/sdc
    number: 1
    state: present

- name: create an ext4 filesystem on /dev/sdc1
  filesystem:
    fstype: ext4
    dev: /dev/sdc1

- name: create nas mount
  mount:
    fstype: ext4
    src: /dev/sdc1
    path: /mnt/nas
    state: mounted

- name: chown nas mount
  file:
    path: /mnt/nas
    mode: 0777