---
# ansible-playbook main.yml -i hosts --tags docker_apps -K
# the binary | this.file | -i targets | *optional --tags | -K asks for sudo pass

- hosts: 'server'
  become: true
  any_errors_fatal: true
#  gather_facts: true
  roles:
    - 'docker'
    - 'docker-compose'
    - 'server'